[package]
name = "valora-demo"
version = "0.1.0"
authors = ["zhaosh <18958728856@189.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
valora = "0.2.12"
num-traits = "0.2"
chrono = "0.4"
